apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hellorancher
  namespace: hello-rancher
 spec:
  rules:
    - host: hellorancher.app.memora.com.br
      http:
        paths:
          - backend:
              service:
                name: hello-rancher
                port:
                  number: 80
            path: /
            pathType: Prefix
